### ISSUE TITLE
Open links in new window

### ISSUE THREAD

**Issue by jniechcial** [emberwatch/emberwatch#212]
From my perspective it would be much easier to use ember watch if the links would open in new window. While using computer it is quite easy to do by myself, but UX-heavy while using iPad. What do you think about that? Opening multiple talks / tutorials for later would be easier.

**Comment by pootsbook** [comment]
Hey Jakub, 

I'm really glad you're finding the collection of resources on EmberWatch useful. I can understand your frustration while browsing on a tablet, it's not as straightforward to open links in new tabs.

Forcing all links to open in a new tab is quite a big change, especially for those visitors for whom this is not the expected behaviour. I am aware that UX opinion on the matter is divided: there are some who believe the visitor should be in control; and there are others that prefer news sites (like EmberWatch) to allow them to ‘load’ their tabs in preparation for consumption.

I am in favour of letting people choose whether or not to open a link in a new tab rather than forcing this behaviour upon them. However, for ‘power users’ like yourself, perhaps it would be beneficial to add an icon / character which links to a new tab:

![ember js talks on emberwatch 2015-10-16 17-53-06](https://cloud.githubusercontent.com/assets/35313/10546539/cf257304-742e-11e5-84d5-6e45d8e6fd29.jpg)
(quick concept only!)

What do you think of a solution like that?

**Comment by jniechcial** [comment]
I find it perfect solution! Totally agree.
